### ISSUE TITLE
BASE_DIR is broken after implementing django-split-settings

### ISSUE THREAD

**Issue by Reve** [wemake-services/django-split-settings#270]
There should be a mention in the documentation that you have to update the BASE_DIR constant in order for language, media and static folders to work.

A crude workaround is to update the path from:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
to
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

**Comment by sobolevn** [comment]
It really depends on how you implement your `BASE_DIR` and how do you store your `split_settings`.

In your case, yes, it should be updated. I don't think that this is addition to the docs is vital, but I would accept a PR from you with the required changes.

**Comment by Reve** [comment]
BASE_DIR is set by django create-project command as a default, this is why I was suggesting a mention in the documentation :)

**Comment by adnathanail** [comment]
Just created a PR to update the README
