### ISSUE TITLE
Argument to optional has incompatible type

### ISSUE THREAD

**Issue by SukiCZ** [wemake-services/django-split-settings#507]
Hello,

My understanding of `optional` is, that it can include a file conditionally. I have a settings file like this:

```py
from os import environ
from split_settings.tools import optional, include

ENV_PRODUCTION = 'production'
ENV_LOCAL = 'local'

ENV = environ['DJANGO_ENV']

include(
    'base.py',
    optional('local_settings.py' if ENV == ENV_LOCAL else None),
)
```

Unfortunately, when running mypy, I get this error:

```
error: Argument 1 to "optional" has incompatible type "str | None"; expected "str"  [arg-type]
```

I believe the argument to `optional` should be `typing.Optional[str]` instead of `str`. Any thoughts on this?

I would love to contribute a PR, if you agree.

Thanks!

**Comment by sobolevn** [comment]
> I would love to contribute a PR, if you agree.

Please :)
